apiVersion: v1
kind: ConfigMap
metadata:
  name: order-schema
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      item TEXT,
      quantity INTEGER,
      user_id TEXT
    );